### ISSUE TITLE
Connect repo to a continuous integration SaaS

### ISSUE THREAD

**Issue by carlschroedl** [pivot-libre/tideman#10]
Consider Travis and Circle CI.

**Comment by carlschroedl** [comment]
Thanks for granting the Travis CI app access to our org! I tried to enable this repo, but it wouldn't let me do it because I don't have admin privileges on the repo. Could you please visit this page and flick the slider to enable Travis to build this repo?

https://travis-ci.org/profile/pivot-libre

**Comment by andrewshell** [comment]
Should be connected now.

**Comment by carlschroedl** [comment]
Looks great. Thanks!
