### ISSUE TITLE
Improve coverage configuration

### ISSUE THREAD

**Issue by carlschroedl** [pivot-libre/tideman#25]
As a developer building the project locally from the command line, I would like the default build command...
```
vendor/bin/phing
```
...to yield a textual description of code coverage so that I can get quick feedback on the project's code coverage without firing up a web browser to view the html coverage. This used to be the behavior. It is not anymore.

As a developer building the project locally, I would like to run a non-default build command to generate HTML code coverage reports so that I can get more detailed feedback on the library's test coverage. Currently this works when running
```
vendor/bin/phing coverage
```
This command, or some similar command should continue to work when work on this issue is done.

As a developer pushing to Github I want the build command that Travis CI runs to output a machine-readable coverage report so that Coveralls visualizes and tracks test coverage. This is the current behavior. It should not regress.

**Comment by andrewshell** [comment]
Running `vendor/bin/phing build-ci` generates text output. Is this what you're looking for?
