### ISSUE TITLE
Add Logging

### ISSUE THREAD

**Issue by carlschroedl** [pivot-libre/tideman#26]
Choose a library for logging, and sprinkle a few appropriately-leveled log statements in a few classes. Strong preference is given to a library that implements the PSR-3 Logging Interface.

At least two candidates:
Monolog
KLogger

If the pivot web app [backend](https://github.com/pivot-libre/pivot) already uses a PSR-3-compliant Logging Library, then that should be used.

**Comment by andrewshell** [comment]
Laravel which is what we're using for the API uses Monolog. We can implement PSR-3 in this library without depending on a specific library. Although we can choose one as a dev dependency if we want to have logging in test scripts.
