### ISSUE TITLE
Tally Margins

### ISSUE THREAD

**Issue by carlschroedl** [pivot-libre/tideman#7]
Given the domain classes created in #6, calculate the margin matrix. Write tests. See https://github.com/carlschroedl/tideman for example data.

**Comment by andrewshell** [comment]
Is this resolved by #23 (merged as #35)?

**Comment by carlschroedl** [comment]
Thanks for checking! While the simpler l methods are pretty thoroughly tested, I only tested the most trivial of cases on the top-level tallying method. I would like to add a few non-trivial cases before we close it.
