### ISSUE TITLE
Return margins in results

### ISSUE THREAD

**Issue by lucasdailey** [pivot-libre/tideman#71]
For use by the front end to draw a table to show the pairwise comparisons.

**Comment by carlschroedl** [comment]
@lucasdailey how many values will there be per table cell?
 * one value showing the difference in support
 * two values showing votes for and against (Like the table titled ["pairwise election results"](https://en.wikipedia.org/wiki/Ranked_pairs#The_situation) on the Ranked Pairs wiki)
 * all three values

**Comment by carlschroedl** [comment]
Partially implemented in #72, #79. Notes on remaining work in comments on #79.

**Comment by carlschroedl** [comment]
Closed by #86
